[package]
name = "ggpr_bin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
bitstream-io = "2.5.0"
bmp-rust = "0.4.1"
godot = { git = "https://github.com/godot-rust/gdext/", branch="master", features = ["register-docs"] }
natord = "1.0.9"
png = "0.17.13"
